import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Card } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { ChevronLeft, ChevronRight, Shuffle, Download, RotateCw } from 'lucide-react';
import { toast } from 'sonner@2.0.3';

interface Flashcard {
  question: string;
  answer: string;
}

interface FlashcardViewerProps {
  flashcards: Flashcard[];
}

export function FlashcardViewer({ flashcards }: FlashcardViewerProps) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [cards, setCards] = useState(flashcards);
  const [shuffleKey, setShuffleKey] = useState(0);

  const handleNext = () => {
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentIndex((prev) => (prev + 1) % cards.length);
    }, 150);
  };

  const handlePrev = () => {
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentIndex((prev) => (prev - 1 + cards.length) % cards.length);
    }, 150);
  };

  const handleShuffle = () => {
    const shuffled = [...cards].sort(() => Math.random() - 0.5);
    setCards(shuffled);
    setCurrentIndex(0);
    setIsFlipped(false);
    setShuffleKey(prev => prev + 1);
    toast.success('Flashcards shuffled!');
  };

  const handleDownload = () => {
    const pdfContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Study Flashcards</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 40px 20px;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
    }
    .header {
      background: white;
      padding: 30px;
      border-radius: 20px;
      margin-bottom: 30px;
      box-shadow: 0 10px 40px rgba(0,0,0,0.1);
    }
    h1 {
      color: #667eea;
      font-size: 36px;
      margin-bottom: 10px;
      display: flex;
      align-items: center;
      gap: 15px;
    }
    .subtitle {
      color: #6b7280;
      font-size: 16px;
    }
    .flashcard {
      background: white;
      border-radius: 20px;
      padding: 30px;
      margin-bottom: 25px;
      box-shadow: 0 10px 40px rgba(0,0,0,0.1);
      page-break-inside: avoid;
      border-left: 6px solid #667eea;
      transition: transform 0.3s;
    }
    .flashcard:hover {
      transform: translateY(-2px);
    }
    .card-number {
      display: inline-block;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 5px 15px;
      border-radius: 20px;
      font-size: 14px;
      margin-bottom: 15px;
    }
    .question {
      font-size: 20px;
      color: #1f2937;
      margin-bottom: 15px;
      font-weight: 600;
      line-height: 1.6;
    }
    .answer {
      color: #4b5563;
      font-size: 16px;
      line-height: 1.8;
      background: #f9fafb;
      padding: 20px;
      border-radius: 12px;
      border-left: 4px solid #a78bfa;
    }
    .footer {
      background: white;
      padding: 25px;
      border-radius: 20px;
      text-align: center;
      margin-top: 30px;
      box-shadow: 0 10px 40px rgba(0,0,0,0.1);
    }
    .stats {
      display: flex;
      justify-content: center;
      gap: 30px;
      margin-bottom: 15px;
    }
    .stat {
      text-align: center;
    }
    .stat-value {
      font-size: 28px;
      font-weight: bold;
      color: #667eea;
    }
    .stat-label {
      font-size: 14px;
      color: #6b7280;
      margin-top: 5px;
    }
    @media print {
      body { background: white; padding: 20px; }
      .flashcard:hover { transform: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📚 Study Flashcards</h1>
      <p class="subtitle">Generated on ${new Date().toLocaleDateString('en-US', { 
        weekday: 'long',
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })}</p>
    </div>
    
    ${cards.map((card, index) => `
      <div class="flashcard">
        <div class="card-number">Card ${index + 1} of ${cards.length}</div>
        <div class="question">❓ ${card.question}</div>
        <div class="answer">✅ ${card.answer}</div>
      </div>
    `).join('')}
    
    <div class="footer">
      <div class="stats">
        <div class="stat">
          <div class="stat-value">${cards.length}</div>
          <div class="stat-label">Total Cards</div>
        </div>
        <div class="stat">
          <div class="stat-value">⭐</div>
          <div class="stat-label">Study Ready</div>
        </div>
      </div>
      <p style="color: #6b7280; font-size: 14px;">
        Generated by Smart Notes Scanner • Personalized Learning Paths
      </p>
    </div>
  </div>
</body>
</html>
    `;

    const blob = new Blob([pdfContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `flashcards_${new Date().getTime()}.html`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success('Flashcards downloaded! Open in browser and print to PDF.');
  };

  const currentCard = cards[currentIndex];

  return (
    <div className="space-y-6">
      {/* Controls */}
      <div className="flex items-center justify-between">
        <Badge className="bg-purple-500/20 text-purple-300 border-purple-500/30 px-4 py-2">
          Card {currentIndex + 1} of {cards.length}
        </Badge>
        <div className="flex gap-2">
          <Button
            size="sm"
            variant="outline"
            onClick={handleShuffle}
            className="border-indigo-500/50 text-indigo-400 hover:bg-indigo-500/10"
          >
            <Shuffle className="w-4 h-4 mr-2" />
            Shuffle
          </Button>
          <Button
            size="sm"
            onClick={handleDownload}
            className="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500"
          >
            <Download className="w-4 h-4 mr-2" />
            Download
          </Button>
        </div>
      </div>

      {/* Flashcard */}
      <div className="relative min-h-[400px] flex items-center justify-center perspective-1000">
        <AnimatePresence mode="wait">
          <motion.div
            key={`${shuffleKey}-${currentIndex}`}
            initial={{ rotateY: 90, opacity: 0, scale: 0.8 }}
            animate={{ rotateY: 0, opacity: 1, scale: 1 }}
            exit={{ rotateY: -90, opacity: 0, scale: 0.8 }}
            transition={{ 
              duration: 0.5,
              type: 'spring',
              stiffness: 100,
              damping: 15
            }}
            className="w-full"
          >
            <motion.div
              onClick={() => setIsFlipped(!isFlipped)}
              className="relative cursor-pointer"
              style={{ transformStyle: 'preserve-3d' }}
            >
              <motion.div
                animate={{ rotateX: isFlipped ? 180 : 0 }}
                transition={{ duration: 0.6, type: 'spring', stiffness: 100 }}
                style={{ transformStyle: 'preserve-3d' }}
                className="relative"
              >
                {/* Front (Question) */}
                <Card
                  className="p-8 bg-gradient-to-br from-indigo-900/40 via-purple-900/40 to-pink-900/40 border-2 border-indigo-500/30 min-h-[400px] flex flex-col items-center justify-center text-center relative overflow-hidden"
                  style={{
                    backfaceVisibility: 'hidden',
                    WebkitBackfaceVisibility: 'hidden',
                  }}
                >
                  {/* Animated background gradient */}
                  <motion.div
                    className="absolute inset-0 opacity-30"
                    animate={{
                      background: [
                        'radial-gradient(circle at 20% 50%, rgba(99, 102, 241, 0.3) 0%, transparent 50%)',
                        'radial-gradient(circle at 80% 50%, rgba(168, 85, 247, 0.3) 0%, transparent 50%)',
                        'radial-gradient(circle at 50% 80%, rgba(236, 72, 153, 0.3) 0%, transparent 50%)',
                        'radial-gradient(circle at 20% 50%, rgba(99, 102, 241, 0.3) 0%, transparent 50%)',
                      ],
                    }}
                    transition={{ duration: 8, repeat: Infinity }}
                  />

                  <div className="relative z-10 w-full">
                    <motion.div
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      transition={{ delay: 0.2, type: 'spring' }}
                      className="w-16 h-16 mx-auto mb-6 rounded-full bg-gradient-to-br from-indigo-500 to-purple-500 flex items-center justify-center"
                    >
                      <span className="text-3xl">❓</span>
                    </motion.div>

                    <motion.div
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.3 }}
                    >
                      <Badge className="mb-4 bg-indigo-500/20 text-indigo-300 border-indigo-500/30">
                        Question
                      </Badge>
                      <h3 className="text-2xl text-white mb-4 px-4">
                        {currentCard.question}
                      </h3>
                    </motion.div>

                    <motion.p
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.5 }}
                      className="text-sm text-gray-400 mt-8"
                    >
                      Click to reveal answer
                    </motion.p>
                  </div>

                  {/* Floating particles */}
                  {[...Array(5)].map((_, i) => (
                    <motion.div
                      key={i}
                      className="absolute w-2 h-2 bg-purple-400 rounded-full"
                      initial={{ 
                        x: Math.random() * 100 + '%',
                        y: Math.random() * 100 + '%',
                        opacity: 0.3
                      }}
                      animate={{
                        y: ['-10%', '110%'],
                        opacity: [0.3, 0.6, 0.3],
                      }}
                      transition={{
                        duration: 3 + i,
                        repeat: Infinity,
                        delay: i * 0.5,
                      }}
                    />
                  ))}
                </Card>

                {/* Back (Answer) */}
                <Card
                  className="absolute top-0 left-0 w-full p-8 bg-gradient-to-br from-purple-900/40 via-pink-900/40 to-indigo-900/40 border-2 border-purple-500/30 min-h-[400px] flex flex-col items-center justify-center text-center overflow-hidden"
                  style={{
                    backfaceVisibility: 'hidden',
                    WebkitBackfaceVisibility: 'hidden',
                    transform: 'rotateX(180deg)',
                  }}
                >
                  {/* Animated background */}
                  <motion.div
                    className="absolute inset-0 opacity-30"
                    animate={{
                      background: [
                        'radial-gradient(circle at 80% 20%, rgba(168, 85, 247, 0.3) 0%, transparent 50%)',
                        'radial-gradient(circle at 20% 80%, rgba(236, 72, 153, 0.3) 0%, transparent 50%)',
                        'radial-gradient(circle at 50% 50%, rgba(99, 102, 241, 0.3) 0%, transparent 50%)',
                        'radial-gradient(circle at 80% 20%, rgba(168, 85, 247, 0.3) 0%, transparent 50%)',
                      ],
                    }}
                    transition={{ duration: 8, repeat: Infinity }}
                  />

                  <div className="relative z-10 w-full">
                    <motion.div
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      transition={{ delay: 0.2, type: 'spring' }}
                      className="w-16 h-16 mx-auto mb-6 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center"
                    >
                      <span className="text-3xl">✅</span>
                    </motion.div>

                    <Badge className="mb-4 bg-purple-500/20 text-purple-300 border-purple-500/30">
                      Answer
                    </Badge>
                    <p className="text-xl text-white leading-relaxed px-4">
                      {currentCard.answer}
                    </p>

                    <motion.div
                      className="mt-8 inline-flex items-center gap-2 text-sm text-gray-400"
                      animate={{ opacity: [0.5, 1, 0.5] }}
                      transition={{ duration: 2, repeat: Infinity }}
                    >
                      <RotateCw className="w-4 h-4" />
                      Click to flip back
                    </motion.div>
                  </div>

                  {/* Success particles */}
                  {[...Array(8)].map((_, i) => (
                    <motion.div
                      key={i}
                      className="absolute text-2xl"
                      initial={{ 
                        x: '50%',
                        y: '50%',
                        opacity: 0,
                        scale: 0
                      }}
                      animate={{
                        x: `${50 + Math.cos((i * Math.PI * 2) / 8) * 40}%`,
                        y: `${50 + Math.sin((i * Math.PI * 2) / 8) * 40}%`,
                        opacity: [0, 1, 0],
                        scale: [0, 1, 0.5],
                      }}
                      transition={{
                        duration: 2,
                        repeat: Infinity,
                        delay: i * 0.2,
                      }}
                    >
                      ✨
                    </motion.div>
                  ))}
                </Card>
              </motion.div>
            </motion.div>
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Navigation */}
      <div className="flex items-center justify-center gap-4">
        <Button
          onClick={handlePrev}
          disabled={cards.length <= 1}
          className="bg-white/5 border border-white/10 hover:bg-white/10 text-white"
        >
          <ChevronLeft className="w-4 h-4 mr-2" />
          Previous
        </Button>

        <div className="flex gap-2">
          {cards.slice(0, Math.min(5, cards.length)).map((_, i) => (
            <motion.button
              key={i}
              onClick={() => {
                setIsFlipped(false);
                setTimeout(() => setCurrentIndex(i), 150);
              }}
              className={`w-3 h-3 rounded-full transition-all ${
                i === currentIndex
                  ? 'bg-gradient-to-r from-indigo-500 to-purple-500 w-8'
                  : 'bg-white/20 hover:bg-white/40'
              }`}
              whileHover={{ scale: 1.2 }}
              whileTap={{ scale: 0.9 }}
            />
          ))}
          {cards.length > 5 && (
            <span className="text-gray-400 text-sm">+{cards.length - 5}</span>
          )}
        </div>

        <Button
          onClick={handleNext}
          disabled={cards.length <= 1}
          className="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white"
        >
          Next
          <ChevronRight className="w-4 h-4 ml-2" />
        </Button>
      </div>

      {/* Progress */}
      <div className="space-y-2">
        <div className="flex justify-between text-sm">
          <span className="text-gray-400">Progress</span>
          <span className="text-purple-400">
            {Math.round(((currentIndex + 1) / cards.length) * 100)}%
          </span>
        </div>
        <div className="h-2 bg-white/5 rounded-full overflow-hidden">
          <motion.div
            className="h-full bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500"
            initial={{ width: 0 }}
            animate={{ width: `${((currentIndex + 1) / cards.length) * 100}%` }}
            transition={{ duration: 0.5 }}
          />
        </div>
      </div>
    </div>
  );
}
