import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Card } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { Download, ZoomIn, ZoomOut, Maximize2, Sparkles, Brain } from 'lucide-react';
import { toast } from 'sonner@2.0.3';

interface MindMapNode {
  id: string;
  label: string;
  children?: MindMapNode[];
  color: string;
  icon?: string;
}

interface MindMapViewerProps {
  text: string;
}

export function MindMapViewer({ text }: MindMapViewerProps) {
  const [mindMap, setMindMap] = useState<MindMapNode | null>(null);
  const [generating, setGenerating] = useState(true);
  const [zoom, setZoom] = useState(1);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);

  useEffect(() => {
    // Simulate AI processing to generate mind map
    const timer = setTimeout(() => {
      const generatedMap = generateMindMap(text);
      setMindMap(generatedMap);
      setGenerating(false);
      toast.success('Mind map generated successfully!');
    }, 2000);

    return () => clearTimeout(timer);
  }, [text]);

  const generateMindMap = (text: string): MindMapNode => {
    // AI-powered mind map generation (simulated)
    // In production, this would call an AI API
    const sentences = text.split(/[.!?]+/).filter(s => s.trim());
    const topics = extractTopics(sentences);

    return {
      id: 'root',
      label: 'Main Topic',
      color: '#6366f1',
      icon: '🎯',
      children: topics.map((topic, i) => ({
        id: `topic-${i}`,
        label: topic.title,
        color: ['#8b5cf6', '#ec4899', '#14b8a6', '#f59e0b'][i % 4],
        icon: ['📚', '💡', '🔬', '🎨'][i % 4],
        children: topic.subtopics.map((sub, j) => ({
          id: `subtopic-${i}-${j}`,
          label: sub,
          color: ['#a78bfa', '#f472b6', '#2dd4bf', '#fbbf24'][i % 4],
        })),
      })),
    };
  };

  const extractTopics = (sentences: string[]) => {
    // Simple topic extraction (in production, use NLP/AI)
    const topics = [];
    let currentTopic = { title: '', subtopics: [] as string[] };
    
    for (let i = 0; i < Math.min(sentences.length, 12); i++) {
      const sentence = sentences[i].trim();
      if (!sentence) continue;

      if (i % 3 === 0) {
        if (currentTopic.title) {
          topics.push(currentTopic);
        }
        currentTopic = {
          title: sentence.length > 40 ? sentence.substring(0, 40) + '...' : sentence,
          subtopics: [],
        };
      } else {
        currentTopic.subtopics.push(
          sentence.length > 50 ? sentence.substring(0, 50) + '...' : sentence
        );
      }
    }
    
    if (currentTopic.title) {
      topics.push(currentTopic);
    }

    return topics.slice(0, 4);
  };

  const handleDownload = () => {
    if (!mindMap) return;

    const svg = generateSVG(mindMap);
    const blob = new Blob([svg], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mindmap_${new Date().getTime()}.svg`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success('Mind map downloaded as SVG!');
  };

  const generateSVG = (node: MindMapNode): string => {
    return `
<svg width="1200" height="800" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#667eea;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#764ba2;stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect width="1200" height="800" fill="url(#grad1)"/>
  <text x="600" y="50" font-family="Arial" font-size="24" fill="white" text-anchor="middle" font-weight="bold">
    ${node.label}
  </text>
  <text x="600" y="400" font-family="Arial" font-size="16" fill="white" text-anchor="middle">
    Mind Map Generated by AI - ${new Date().toLocaleDateString()}
  </text>
</svg>
    `;
  };

  if (generating) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <motion.div
          className="relative w-32 h-32 mb-6"
          animate={{ rotate: 360 }}
          transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
        >
          <div className="absolute inset-0 rounded-full border-4 border-purple-500/20" />
          <motion.div
            className="absolute inset-0 rounded-full border-4 border-transparent border-t-purple-500"
            animate={{ rotate: -360 }}
            transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }}
          />
          <div className="absolute inset-0 flex items-center justify-center">
            <Brain className="w-12 h-12 text-purple-400" />
          </div>
        </motion.div>

        <motion.h3
          className="text-xl text-white mb-2"
          animate={{ opacity: [0.5, 1, 0.5] }}
          transition={{ duration: 2, repeat: Infinity }}
        >
          AI Generating Mind Map...
        </motion.h3>
        <p className="text-gray-400 text-center max-w-md">
          Analyzing your notes and creating an intelligent visual structure
        </p>

        {/* Animated processing steps */}
        <div className="mt-8 space-y-3">
          {[
            { label: 'Analyzing content', delay: 0 },
            { label: 'Extracting key concepts', delay: 0.5 },
            { label: 'Building relationships', delay: 1 },
            { label: 'Optimizing layout', delay: 1.5 },
          ].map((step, i) => (
            <motion.div
              key={step.label}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: step.delay }}
              className="flex items-center gap-3 text-gray-300"
            >
              <motion.div
                className="w-2 h-2 rounded-full bg-purple-500"
                animate={{
                  scale: [1, 1.5, 1],
                  opacity: [0.5, 1, 0.5],
                }}
                transition={{
                  duration: 1.5,
                  repeat: Infinity,
                  delay: step.delay,
                }}
              />
              <span>{step.label}</span>
            </motion.div>
          ))}
        </div>
      </div>
    );
  }

  if (!mindMap) return null;

  return (
    <div className="space-y-6">
      {/* Controls */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Badge className="bg-gradient-to-r from-indigo-500/20 to-purple-500/20 text-purple-300 border-purple-500/30 px-4 py-2">
            <Sparkles className="w-4 h-4 mr-2" />
            AI-Powered Mind Map
          </Badge>
        </div>
        
        <div className="flex gap-2">
          <Button
            size="sm"
            variant="outline"
            onClick={() => setZoom(Math.max(0.5, zoom - 0.1))}
            className="border-white/10 text-gray-400 hover:bg-white/5"
          >
            <ZoomOut className="w-4 h-4" />
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => setZoom(Math.min(2, zoom + 0.1))}
            className="border-white/10 text-gray-400 hover:bg-white/5"
          >
            <ZoomIn className="w-4 h-4" />
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => setZoom(1)}
            className="border-white/10 text-gray-400 hover:bg-white/5"
          >
            <Maximize2 className="w-4 h-4" />
          </Button>
          <Button
            size="sm"
            onClick={handleDownload}
            className="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500"
          >
            <Download className="w-4 h-4 mr-2" />
            Download SVG
          </Button>
        </div>
      </div>

      {/* Mind Map */}
      <Card className="p-8 bg-gradient-to-br from-slate-900/80 via-purple-900/20 to-slate-900/80 border border-white/10 min-h-[600px] overflow-hidden relative">
        {/* Animated background */}
        <div className="absolute inset-0 opacity-20">
          {[...Array(20)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute w-1 h-1 bg-purple-400 rounded-full"
              initial={{
                x: Math.random() * 100 + '%',
                y: Math.random() * 100 + '%',
              }}
              animate={{
                y: ['-5%', '105%'],
                opacity: [0, 1, 0],
              }}
              transition={{
                duration: 5 + Math.random() * 5,
                repeat: Infinity,
                delay: Math.random() * 5,
              }}
            />
          ))}
        </div>

        {/* Mind map content */}
        <motion.div
          className="relative"
          style={{ scale: zoom }}
          transition={{ duration: 0.3 }}
        >
          <div className="flex flex-col items-center">
            {/* Root node */}
            <motion.div
              initial={{ scale: 0, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ type: 'spring', stiffness: 200, delay: 0.2 }}
              whileHover={{ scale: 1.05 }}
              onClick={() => setSelectedNode(mindMap.id)}
              className="cursor-pointer"
            >
              <Card className={`p-6 bg-gradient-to-br from-indigo-600 to-purple-600 border-2 ${
                selectedNode === mindMap.id ? 'border-yellow-400 shadow-lg shadow-yellow-400/50' : 'border-white/20'
              } min-w-[200px] text-center relative overflow-hidden group`}>
                <motion.div
                  className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent"
                  initial={{ x: '-100%' }}
                  animate={{ x: '200%' }}
                  transition={{ duration: 2, repeat: Infinity, repeatDelay: 3 }}
                />
                <div className="relative z-10">
                  <div className="text-4xl mb-2">{mindMap.icon}</div>
                  <h3 className="text-white">{mindMap.label}</h3>
                </div>
              </Card>
            </motion.div>

            {/* Connecting lines and child nodes */}
            {mindMap.children && mindMap.children.length > 0 && (
              <div className="mt-8 w-full">
                {/* Connection lines */}
                <svg className="absolute left-0 right-0 h-20" style={{ top: '140px' }}>
                  {mindMap.children.map((_, i) => {
                    const totalChildren = mindMap.children!.length;
                    const startX = 50;
                    const endX = (100 / (totalChildren + 1)) * (i + 1);
                    
                    return (
                      <motion.path
                        key={i}
                        d={`M ${startX}% 0 Q ${startX}% 50, ${endX}% 100`}
                        stroke="url(#gradient)"
                        strokeWidth="2"
                        fill="none"
                        initial={{ pathLength: 0, opacity: 0 }}
                        animate={{ pathLength: 1, opacity: 0.4 }}
                        transition={{ duration: 0.8, delay: 0.3 + i * 0.1 }}
                      />
                    );
                  })}
                  <defs>
                    <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%">
                      <stop offset="0%" stopColor="#6366f1" />
                      <stop offset="50%" stopColor="#8b5cf6" />
                      <stop offset="100%" stopColor="#ec4899" />
                    </linearGradient>
                  </defs>
                </svg>

                {/* Child nodes */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-24">
                  {mindMap.children.map((child, i) => (
                    <motion.div
                      key={child.id}
                      initial={{ scale: 0, opacity: 0, y: 50 }}
                      animate={{ scale: 1, opacity: 1, y: 0 }}
                      transition={{
                        type: 'spring',
                        stiffness: 150,
                        delay: 0.4 + i * 0.1,
                      }}
                      className="flex flex-col items-center"
                    >
                      {/* Parent topic */}
                      <motion.div
                        whileHover={{ scale: 1.05, rotate: 2 }}
                        onClick={() => setSelectedNode(child.id)}
                        className="cursor-pointer w-full"
                      >
                        <Card
                          className={`p-4 border-2 ${
                            selectedNode === child.id
                              ? 'border-yellow-400 shadow-lg shadow-yellow-400/50'
                              : 'border-white/20'
                          } text-center relative overflow-hidden group`}
                          style={{
                            background: `linear-gradient(135deg, ${child.color}40, ${child.color}20)`,
                          }}
                        >
                          <motion.div
                            className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity"
                            style={{
                              background: `radial-gradient(circle at center, ${child.color}40, transparent)`,
                            }}
                          />
                          <div className="relative z-10">
                            <div className="text-3xl mb-2">{child.icon}</div>
                            <p className="text-white text-sm">{child.label}</p>
                          </div>
                        </Card>
                      </motion.div>

                      {/* Subtopics */}
                      {child.children && child.children.length > 0 && (
                        <div className="mt-4 space-y-2 w-full">
                          {child.children.map((subchild, j) => (
                            <motion.div
                              key={subchild.id}
                              initial={{ scale: 0, opacity: 0, x: -20 }}
                              animate={{ scale: 1, opacity: 1, x: 0 }}
                              transition={{
                                type: 'spring',
                                delay: 0.6 + i * 0.1 + j * 0.05,
                              }}
                              whileHover={{ scale: 1.02, x: 5 }}
                              onClick={() => setSelectedNode(subchild.id)}
                              className="cursor-pointer"
                            >
                              <Card
                                className={`p-3 border ${
                                  selectedNode === subchild.id
                                    ? 'border-yellow-400 bg-yellow-400/10'
                                    : 'border-white/10 bg-white/5'
                                } backdrop-blur-sm hover:bg-white/10 transition-all`}
                              >
                                <p className="text-gray-300 text-xs leading-relaxed">
                                  {subchild.label}
                                </p>
                              </Card>
                            </motion.div>
                          ))}
                        </div>
                      )}
                    </motion.div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </motion.div>

        {/* Glow effect */}
        <motion.div
          className="absolute -inset-20 opacity-30"
          animate={{
            background: [
              'radial-gradient(circle at 20% 20%, #6366f1 0%, transparent 50%)',
              'radial-gradient(circle at 80% 80%, #8b5cf6 0%, transparent 50%)',
              'radial-gradient(circle at 50% 50%, #ec4899 0%, transparent 50%)',
              'radial-gradient(circle at 20% 20%, #6366f1 0%, transparent 50%)',
            ],
          }}
          transition={{ duration: 10, repeat: Infinity }}
        />
      </Card>

      {/* Legend */}
      <Card className="p-4 bg-white/5 backdrop-blur-sm border-white/10">
        <div className="flex items-center justify-between text-sm">
          <div className="flex items-center gap-4">
            <span className="text-gray-400">Click nodes to highlight</span>
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-indigo-500" />
              <span className="text-gray-400">Main Topic</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-purple-500" />
              <span className="text-gray-400">Subtopics</span>
            </div>
          </div>
          <Badge className="bg-green-500/20 text-green-400 border-green-500/30">
            Zoom: {Math.round(zoom * 100)}%
          </Badge>
        </div>
      </Card>
    </div>
  );
}
